export * from './adminResource.service';
import { AdminResourceService } from './adminResource.service';
export * from './eventResource.service';
import { EventResourceService } from './eventResource.service';
export * from './healthCheckResource.service';
import { HealthCheckResourceService } from './healthCheckResource.service';
export * from './metadataResource.service';
import { MetadataResourceService } from './metadataResource.service';
export * from './queueAdminResource.service';
import { QueueAdminResourceService } from './queueAdminResource.service';
export * from './taskResource.service';
import { TaskResourceService } from './taskResource.service';
export * from './workflowBulkResource.service';
import { WorkflowBulkResourceService } from './workflowBulkResource.service';
export * from './workflowResource.service';
import { WorkflowResourceService } from './workflowResource.service';
export const APIS = [AdminResourceService, EventResourceService, HealthCheckResourceService, MetadataResourceService, QueueAdminResourceService, TaskResourceService, WorkflowBulkResourceService, WorkflowResourceService];
