/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ExternalStorageLocation } from '../model/externalStorageLocation';
import { PollData } from '../model/pollData';
import { SearchResultTaskSummary } from '../model/searchResultTaskSummary';
import { Task } from '../model/task';
import { TaskExecLog } from '../model/taskExecLog';
import { TaskResult } from '../model/taskResult';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TaskManagementService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Ack Task is received
     * 
     * @param taskId 
     * @param workerid 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public ack(taskId: string, workerid?: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public ack(taskId: string, workerid?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public ack(taskId: string, workerid?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public ack(taskId: string, workerid?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling ack.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (workerid !== undefined) {
            queryParameters = queryParameters.set('workerid', <any>workerid);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.post<string>(`${this.basePath}/tasks/${encodeURIComponent(String(taskId))}/ack`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the details about each queue
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public all(observe?: 'body', reportProgress?: boolean): Observable<{ [key: string]: number; }>;
    public all(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<{ [key: string]: number; }>>;
    public all(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<{ [key: string]: number; }>>;
    public all(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.get<{ [key: string]: number; }>(`${this.basePath}/tasks/queue/all`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the details about each queue
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public allVerbose(observe?: 'body', reportProgress?: boolean): Observable<{ [key: string]: { [key: string]: { [key: string]: number; }; }; }>;
    public allVerbose(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<{ [key: string]: { [key: string]: { [key: string]: number; }; }; }>>;
    public allVerbose(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<{ [key: string]: { [key: string]: { [key: string]: number; }; }; }>>;
    public allVerbose(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.get<{ [key: string]: { [key: string]: { [key: string]: number; }; }; }>(`${this.basePath}/tasks/queue/all/verbose`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * batch Poll for a task of a certain type
     * 
     * @param tasktype 
     * @param workerid 
     * @param domain 
     * @param count 
     * @param timeout 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public batchPoll(tasktype: string, workerid?: string, domain?: string, count?: number, timeout?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Task>>;
    public batchPoll(tasktype: string, workerid?: string, domain?: string, count?: number, timeout?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Task>>>;
    public batchPoll(tasktype: string, workerid?: string, domain?: string, count?: number, timeout?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Task>>>;
    public batchPoll(tasktype: string, workerid?: string, domain?: string, count?: number, timeout?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (tasktype === null || tasktype === undefined) {
            throw new Error('Required parameter tasktype was null or undefined when calling batchPoll.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (workerid !== undefined) {
            queryParameters = queryParameters.set('workerid', <any>workerid);
        }
        if (domain !== undefined) {
            queryParameters = queryParameters.set('domain', <any>domain);
        }
        if (count !== undefined) {
            queryParameters = queryParameters.set('count', <any>count);
        }
        if (timeout !== undefined) {
            queryParameters = queryParameters.set('timeout', <any>timeout);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.get<Array<Task>>(`${this.basePath}/tasks/poll/batch/${encodeURIComponent(String(tasktype))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the last poll data for all task types
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPollData(observe?: 'body', reportProgress?: boolean): Observable<Array<PollData>>;
    public getAllPollData(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PollData>>>;
    public getAllPollData(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PollData>>>;
    public getAllPollData(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.get<Array<PollData>>(`${this.basePath}/tasks/queue/polldata/all`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the external uri where the task payload is to be stored
     * 
     * @param path 
     * @param operation 
     * @param payloadType 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExternalStorageLocation(path?: string, operation?: string, payloadType?: string, observe?: 'body', reportProgress?: boolean): Observable<ExternalStorageLocation>;
    public getExternalStorageLocation(path?: string, operation?: string, payloadType?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ExternalStorageLocation>>;
    public getExternalStorageLocation(path?: string, operation?: string, payloadType?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ExternalStorageLocation>>;
    public getExternalStorageLocation(path?: string, operation?: string, payloadType?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (path !== undefined) {
            queryParameters = queryParameters.set('path', <any>path);
        }
        if (operation !== undefined) {
            queryParameters = queryParameters.set('operation', <any>operation);
        }
        if (payloadType !== undefined) {
            queryParameters = queryParameters.set('payloadType', <any>payloadType);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.get<ExternalStorageLocation>(`${this.basePath}/tasks/externalstoragelocation`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get in progress task for a given workflow id.
     * 
     * @param workflowId 
     * @param taskRefName 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPendingTaskForWorkflow(workflowId: string, taskRefName: string, observe?: 'body', reportProgress?: boolean): Observable<Task>;
    public getPendingTaskForWorkflow(workflowId: string, taskRefName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Task>>;
    public getPendingTaskForWorkflow(workflowId: string, taskRefName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Task>>;
    public getPendingTaskForWorkflow(workflowId: string, taskRefName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (workflowId === null || workflowId === undefined) {
            throw new Error('Required parameter workflowId was null or undefined when calling getPendingTaskForWorkflow.');
        }
        if (taskRefName === null || taskRefName === undefined) {
            throw new Error('Required parameter taskRefName was null or undefined when calling getPendingTaskForWorkflow.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.get<Task>(`${this.basePath}/tasks/in_progress/${encodeURIComponent(String(workflowId))}/${encodeURIComponent(String(taskRefName))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the last poll data for a given task type
     * 
     * @param taskType 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPollData(taskType?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<PollData>>;
    public getPollData(taskType?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PollData>>>;
    public getPollData(taskType?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PollData>>>;
    public getPollData(taskType?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (taskType !== undefined) {
            queryParameters = queryParameters.set('taskType', <any>taskType);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.get<Array<PollData>>(`${this.basePath}/tasks/queue/polldata`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get task by Id
     * 
     * @param taskId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTask(taskId: string, observe?: 'body', reportProgress?: boolean): Observable<Task>;
    public getTask(taskId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Task>>;
    public getTask(taskId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Task>>;
    public getTask(taskId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling getTask.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.get<Task>(`${this.basePath}/tasks/${encodeURIComponent(String(taskId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Task Execution Logs
     * 
     * @param taskId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTaskLogs(taskId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<TaskExecLog>>;
    public getTaskLogs(taskId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TaskExecLog>>>;
    public getTaskLogs(taskId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TaskExecLog>>>;
    public getTaskLogs(taskId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling getTaskLogs.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<TaskExecLog>>(`${this.basePath}/tasks/${encodeURIComponent(String(taskId))}/log`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get in progress tasks. The results are paginated.
     * 
     * @param tasktype 
     * @param startKey 
     * @param count 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTasks(tasktype: string, startKey?: string, count?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Task>>;
    public getTasks(tasktype: string, startKey?: string, count?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Task>>>;
    public getTasks(tasktype: string, startKey?: string, count?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Task>>>;
    public getTasks(tasktype: string, startKey?: string, count?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (tasktype === null || tasktype === undefined) {
            throw new Error('Required parameter tasktype was null or undefined when calling getTasks.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (startKey !== undefined) {
            queryParameters = queryParameters.set('startKey', <any>startKey);
        }
        if (count !== undefined) {
            queryParameters = queryParameters.set('count', <any>count);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.get<Array<Task>>(`${this.basePath}/tasks/in_progress/${encodeURIComponent(String(tasktype))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Log Task Execution Details
     * 
     * @param taskId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public log(taskId: string, body?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public log(taskId: string, body?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public log(taskId: string, body?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public log(taskId: string, body?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling log.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/tasks/${encodeURIComponent(String(taskId))}/log`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Poll for a task of a certain type
     * 
     * @param tasktype 
     * @param workerid 
     * @param domain 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public poll(tasktype: string, workerid?: string, domain?: string, observe?: 'body', reportProgress?: boolean): Observable<Task>;
    public poll(tasktype: string, workerid?: string, domain?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Task>>;
    public poll(tasktype: string, workerid?: string, domain?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Task>>;
    public poll(tasktype: string, workerid?: string, domain?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (tasktype === null || tasktype === undefined) {
            throw new Error('Required parameter tasktype was null or undefined when calling poll.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (workerid !== undefined) {
            queryParameters = queryParameters.set('workerid', <any>workerid);
        }
        if (domain !== undefined) {
            queryParameters = queryParameters.set('domain', <any>domain);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.get<Task>(`${this.basePath}/tasks/poll/${encodeURIComponent(String(tasktype))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Remove Task from a Task type queue
     * 
     * @param taskType 
     * @param taskId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public removeTaskFromQueue(taskType: string, taskId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public removeTaskFromQueue(taskType: string, taskId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public removeTaskFromQueue(taskType: string, taskId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public removeTaskFromQueue(taskType: string, taskId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (taskType === null || taskType === undefined) {
            throw new Error('Required parameter taskType was null or undefined when calling removeTaskFromQueue.');
        }
        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling removeTaskFromQueue.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/tasks/queue/${encodeURIComponent(String(taskType))}/${encodeURIComponent(String(taskId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Requeue pending tasks for all the running workflows
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public requeue(observe?: 'body', reportProgress?: boolean): Observable<string>;
    public requeue(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public requeue(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public requeue(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<string>(`${this.basePath}/tasks/queue/requeue`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Requeue pending tasks
     * 
     * @param taskType 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public requeuePendingTask(taskType: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public requeuePendingTask(taskType: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public requeuePendingTask(taskType: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public requeuePendingTask(taskType: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (taskType === null || taskType === undefined) {
            throw new Error('Required parameter taskType was null or undefined when calling requeuePendingTask.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.post<string>(`${this.basePath}/tasks/queue/requeue/${encodeURIComponent(String(taskType))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Search for tasks based in payload and other parameters
     * use sort options as sort&#x3D;&lt;field&gt;:ASC|DESC e.g. sort&#x3D;name&amp;sort&#x3D;workflowId:DESC. If order is not specified, defaults to ASC
     * @param start 
     * @param size 
     * @param sort 
     * @param freeText 
     * @param query 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public search(start?: number, size?: number, sort?: string, freeText?: string, query?: string, observe?: 'body', reportProgress?: boolean): Observable<SearchResultTaskSummary>;
    public search(start?: number, size?: number, sort?: string, freeText?: string, query?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchResultTaskSummary>>;
    public search(start?: number, size?: number, sort?: string, freeText?: string, query?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchResultTaskSummary>>;
    public search(start?: number, size?: number, sort?: string, freeText?: string, query?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (start !== undefined) {
            queryParameters = queryParameters.set('start', <any>start);
        }
        if (size !== undefined) {
            queryParameters = queryParameters.set('size', <any>size);
        }
        if (sort !== undefined) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }
        if (freeText !== undefined) {
            queryParameters = queryParameters.set('freeText', <any>freeText);
        }
        if (query !== undefined) {
            queryParameters = queryParameters.set('query', <any>query);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.get<SearchResultTaskSummary>(`${this.basePath}/tasks/search`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Task type queue sizes
     * 
     * @param taskType 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public size(taskType?: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<{ [key: string]: number; }>;
    public size(taskType?: Array<string>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<{ [key: string]: number; }>>;
    public size(taskType?: Array<string>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<{ [key: string]: number; }>>;
    public size(taskType?: Array<string>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (taskType) {
            taskType.forEach((element) => {
                queryParameters = queryParameters.append('taskType', <any>element);
            })
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            '*/*'
        ];

        return this.httpClient.get<{ [key: string]: number; }>(`${this.basePath}/tasks/queue/sizes`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a task
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateTask(body?: TaskResult, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public updateTask(body?: TaskResult, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public updateTask(body?: TaskResult, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public updateTask(body?: TaskResult, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<string>(`${this.basePath}/tasks`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
