/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ExternalStorageLocation } from '../model/externalStorageLocation';
import { RerunWorkflowRequest } from '../model/rerunWorkflowRequest';
import { SearchResultWorkflowSummary } from '../model/searchResultWorkflowSummary';
import { SkipTaskRequest } from '../model/skipTaskRequest';
import { StartWorkflowRequest } from '../model/startWorkflowRequest';
import { Workflow } from '../model/workflow';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class WorkflowResourceService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Removes the workflow from the system
     * 
     * @param workflowId 
     * @param archiveWorkflow 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public _delete(workflowId: string, archiveWorkflow?: boolean, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public _delete(workflowId: string, archiveWorkflow?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public _delete(workflowId: string, archiveWorkflow?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public _delete(workflowId: string, archiveWorkflow?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workflowId === null || workflowId === undefined) {
            throw new Error('Required parameter workflowId was null or undefined when calling _delete.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (archiveWorkflow !== undefined && archiveWorkflow !== null) {
            queryParameters = queryParameters.set('archiveWorkflow', <any>archiveWorkflow);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/api/workflow/${encodeURIComponent(String(workflowId))}/remove`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Starts the decision task for a workflow
     * 
     * @param workflowId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public decide(workflowId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public decide(workflowId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public decide(workflowId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public decide(workflowId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workflowId === null || workflowId === undefined) {
            throw new Error('Required parameter workflowId was null or undefined when calling decide.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('put',`${this.basePath}/api/workflow/decide/${encodeURIComponent(String(workflowId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets the workflow by workflow id
     * 
     * @param workflowId 
     * @param includeTasks 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExecutionStatus(workflowId: string, includeTasks?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Workflow>;
    public getExecutionStatus(workflowId: string, includeTasks?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Workflow>>;
    public getExecutionStatus(workflowId: string, includeTasks?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Workflow>>;
    public getExecutionStatus(workflowId: string, includeTasks?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workflowId === null || workflowId === undefined) {
            throw new Error('Required parameter workflowId was null or undefined when calling getExecutionStatus.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (includeTasks !== undefined && includeTasks !== null) {
            queryParameters = queryParameters.set('includeTasks', <any>includeTasks);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Workflow>('get',`${this.basePath}/api/workflow/${encodeURIComponent(String(workflowId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the uri and path of the external storage where the workflow payload is to be stored
     * 
     * @param path 
     * @param operation 
     * @param payloadType 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExternalStorageLocation1(path: string, operation: string, payloadType: string, observe?: 'body', reportProgress?: boolean): Observable<ExternalStorageLocation>;
    public getExternalStorageLocation1(path: string, operation: string, payloadType: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ExternalStorageLocation>>;
    public getExternalStorageLocation1(path: string, operation: string, payloadType: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ExternalStorageLocation>>;
    public getExternalStorageLocation1(path: string, operation: string, payloadType: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (path === null || path === undefined) {
            throw new Error('Required parameter path was null or undefined when calling getExternalStorageLocation1.');
        }

        if (operation === null || operation === undefined) {
            throw new Error('Required parameter operation was null or undefined when calling getExternalStorageLocation1.');
        }

        if (payloadType === null || payloadType === undefined) {
            throw new Error('Required parameter payloadType was null or undefined when calling getExternalStorageLocation1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (path !== undefined && path !== null) {
            queryParameters = queryParameters.set('path', <any>path);
        }
        if (operation !== undefined && operation !== null) {
            queryParameters = queryParameters.set('operation', <any>operation);
        }
        if (payloadType !== undefined && payloadType !== null) {
            queryParameters = queryParameters.set('payloadType', <any>payloadType);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ExternalStorageLocation>('get',`${this.basePath}/api/workflow/externalstoragelocation`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve all the running workflows
     * 
     * @param name 
     * @param version 
     * @param startTime 
     * @param endTime 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRunningWorkflow(name: string, version?: number, startTime?: number, endTime?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<string>>;
    public getRunningWorkflow(name: string, version?: number, startTime?: number, endTime?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<string>>>;
    public getRunningWorkflow(name: string, version?: number, startTime?: number, endTime?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<string>>>;
    public getRunningWorkflow(name: string, version?: number, startTime?: number, endTime?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling getRunningWorkflow.');
        }




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (version !== undefined && version !== null) {
            queryParameters = queryParameters.set('version', <any>version);
        }
        if (startTime !== undefined && startTime !== null) {
            queryParameters = queryParameters.set('startTime', <any>startTime);
        }
        if (endTime !== undefined && endTime !== null) {
            queryParameters = queryParameters.set('endTime', <any>endTime);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<string>>('get',`${this.basePath}/api/workflow/running/${encodeURIComponent(String(name))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Lists workflows for the given correlation id
     * 
     * @param name 
     * @param correlationId 
     * @param includeClosed 
     * @param includeTasks 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getWorkflows(name: string, correlationId: string, includeClosed?: boolean, includeTasks?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Array<Workflow>>;
    public getWorkflows(name: string, correlationId: string, includeClosed?: boolean, includeTasks?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Workflow>>>;
    public getWorkflows(name: string, correlationId: string, includeClosed?: boolean, includeTasks?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Workflow>>>;
    public getWorkflows(name: string, correlationId: string, includeClosed?: boolean, includeTasks?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling getWorkflows.');
        }

        if (correlationId === null || correlationId === undefined) {
            throw new Error('Required parameter correlationId was null or undefined when calling getWorkflows.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (includeClosed !== undefined && includeClosed !== null) {
            queryParameters = queryParameters.set('includeClosed', <any>includeClosed);
        }
        if (includeTasks !== undefined && includeTasks !== null) {
            queryParameters = queryParameters.set('includeTasks', <any>includeTasks);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Workflow>>('get',`${this.basePath}/api/workflow/${encodeURIComponent(String(name))}/correlated/${encodeURIComponent(String(correlationId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Lists workflows for the given correlation id list
     * 
     * @param body 
     * @param name 
     * @param includeClosed 
     * @param includeTasks 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getWorkflows1(body: Array<string>, name: string, includeClosed?: boolean, includeTasks?: boolean, observe?: 'body', reportProgress?: boolean): Observable<{ [key: string]: Array<Workflow>; }>;
    public getWorkflows1(body: Array<string>, name: string, includeClosed?: boolean, includeTasks?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<{ [key: string]: Array<Workflow>; }>>;
    public getWorkflows1(body: Array<string>, name: string, includeClosed?: boolean, includeTasks?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<{ [key: string]: Array<Workflow>; }>>;
    public getWorkflows1(body: Array<string>, name: string, includeClosed?: boolean, includeTasks?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getWorkflows1.');
        }

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling getWorkflows1.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (includeClosed !== undefined && includeClosed !== null) {
            queryParameters = queryParameters.set('includeClosed', <any>includeClosed);
        }
        if (includeTasks !== undefined && includeTasks !== null) {
            queryParameters = queryParameters.set('includeTasks', <any>includeTasks);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<{ [key: string]: Array<Workflow>; }>('post',`${this.basePath}/api/workflow/${encodeURIComponent(String(name))}/correlated`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Pauses the workflow
     * 
     * @param workflowId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public pauseWorkflow1(workflowId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public pauseWorkflow1(workflowId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public pauseWorkflow1(workflowId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public pauseWorkflow1(workflowId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workflowId === null || workflowId === undefined) {
            throw new Error('Required parameter workflowId was null or undefined when calling pauseWorkflow1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('put',`${this.basePath}/api/workflow/${encodeURIComponent(String(workflowId))}/pause`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Reruns the workflow from a specific task
     * 
     * @param body 
     * @param workflowId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public rerun(body: RerunWorkflowRequest, workflowId: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public rerun(body: RerunWorkflowRequest, workflowId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public rerun(body: RerunWorkflowRequest, workflowId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public rerun(body: RerunWorkflowRequest, workflowId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling rerun.');
        }

        if (workflowId === null || workflowId === undefined) {
            throw new Error('Required parameter workflowId was null or undefined when calling rerun.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<string>('post',`${this.basePath}/api/workflow/${encodeURIComponent(String(workflowId))}/rerun`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Resets callback times of all non-terminal SIMPLE tasks to 0
     * 
     * @param workflowId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public resetWorkflow(workflowId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public resetWorkflow(workflowId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public resetWorkflow(workflowId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public resetWorkflow(workflowId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workflowId === null || workflowId === undefined) {
            throw new Error('Required parameter workflowId was null or undefined when calling resetWorkflow.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('post',`${this.basePath}/api/workflow/${encodeURIComponent(String(workflowId))}/resetcallbacks`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restarts a completed workflow
     * 
     * @param workflowId 
     * @param useLatestDefinitions 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public restart1(workflowId: string, useLatestDefinitions?: boolean, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public restart1(workflowId: string, useLatestDefinitions?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public restart1(workflowId: string, useLatestDefinitions?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public restart1(workflowId: string, useLatestDefinitions?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workflowId === null || workflowId === undefined) {
            throw new Error('Required parameter workflowId was null or undefined when calling restart1.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (useLatestDefinitions !== undefined && useLatestDefinitions !== null) {
            queryParameters = queryParameters.set('useLatestDefinitions', <any>useLatestDefinitions);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('post',`${this.basePath}/api/workflow/${encodeURIComponent(String(workflowId))}/restart`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Resumes the workflow
     * 
     * @param workflowId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public resumeWorkflow1(workflowId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public resumeWorkflow1(workflowId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public resumeWorkflow1(workflowId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public resumeWorkflow1(workflowId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workflowId === null || workflowId === undefined) {
            throw new Error('Required parameter workflowId was null or undefined when calling resumeWorkflow1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('put',`${this.basePath}/api/workflow/${encodeURIComponent(String(workflowId))}/resume`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retries the last failed task
     * 
     * @param workflowId 
     * @param resumeSubworkflowTasks 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public retry1(workflowId: string, resumeSubworkflowTasks?: boolean, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public retry1(workflowId: string, resumeSubworkflowTasks?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public retry1(workflowId: string, resumeSubworkflowTasks?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public retry1(workflowId: string, resumeSubworkflowTasks?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workflowId === null || workflowId === undefined) {
            throw new Error('Required parameter workflowId was null or undefined when calling retry1.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (resumeSubworkflowTasks !== undefined && resumeSubworkflowTasks !== null) {
            queryParameters = queryParameters.set('resumeSubworkflowTasks', <any>resumeSubworkflowTasks);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('post',`${this.basePath}/api/workflow/${encodeURIComponent(String(workflowId))}/retry`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Search for workflows based on payload and other parameters
     * use sort options as sort&#x3D;&lt;field&gt;:ASC|DESC e.g. sort&#x3D;name&amp;sort&#x3D;workflowId:DESC. If order is not specified, defaults to ASC.
     * @param start 
     * @param size 
     * @param sort 
     * @param freeText 
     * @param query 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public search1(start?: number, size?: number, sort?: string, freeText?: string, query?: string, observe?: 'body', reportProgress?: boolean): Observable<SearchResultWorkflowSummary>;
    public search1(start?: number, size?: number, sort?: string, freeText?: string, query?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchResultWorkflowSummary>>;
    public search1(start?: number, size?: number, sort?: string, freeText?: string, query?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchResultWorkflowSummary>>;
    public search1(start?: number, size?: number, sort?: string, freeText?: string, query?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (start !== undefined && start !== null) {
            queryParameters = queryParameters.set('start', <any>start);
        }
        if (size !== undefined && size !== null) {
            queryParameters = queryParameters.set('size', <any>size);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }
        if (freeText !== undefined && freeText !== null) {
            queryParameters = queryParameters.set('freeText', <any>freeText);
        }
        if (query !== undefined && query !== null) {
            queryParameters = queryParameters.set('query', <any>query);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SearchResultWorkflowSummary>('get',`${this.basePath}/api/workflow/search`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Search for workflows based on task parameters
     * use sort options as sort&#x3D;&lt;field&gt;:ASC|DESC e.g. sort&#x3D;name&amp;sort&#x3D;workflowId:DESC. If order is not specified, defaults to ASC
     * @param start 
     * @param size 
     * @param sort 
     * @param freeText 
     * @param query 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchWorkflowsByTasks(start?: number, size?: number, sort?: string, freeText?: string, query?: string, observe?: 'body', reportProgress?: boolean): Observable<SearchResultWorkflowSummary>;
    public searchWorkflowsByTasks(start?: number, size?: number, sort?: string, freeText?: string, query?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchResultWorkflowSummary>>;
    public searchWorkflowsByTasks(start?: number, size?: number, sort?: string, freeText?: string, query?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchResultWorkflowSummary>>;
    public searchWorkflowsByTasks(start?: number, size?: number, sort?: string, freeText?: string, query?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (start !== undefined && start !== null) {
            queryParameters = queryParameters.set('start', <any>start);
        }
        if (size !== undefined && size !== null) {
            queryParameters = queryParameters.set('size', <any>size);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }
        if (freeText !== undefined && freeText !== null) {
            queryParameters = queryParameters.set('freeText', <any>freeText);
        }
        if (query !== undefined && query !== null) {
            queryParameters = queryParameters.set('query', <any>query);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SearchResultWorkflowSummary>('get',`${this.basePath}/api/workflow/search-by-tasks`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Skips a given task from a current running workflow
     * 
     * @param workflowId 
     * @param taskReferenceName 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public skipTaskFromWorkflow(workflowId: string, taskReferenceName: string, body?: SkipTaskRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public skipTaskFromWorkflow(workflowId: string, taskReferenceName: string, body?: SkipTaskRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public skipTaskFromWorkflow(workflowId: string, taskReferenceName: string, body?: SkipTaskRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public skipTaskFromWorkflow(workflowId: string, taskReferenceName: string, body?: SkipTaskRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workflowId === null || workflowId === undefined) {
            throw new Error('Required parameter workflowId was null or undefined when calling skipTaskFromWorkflow.');
        }

        if (taskReferenceName === null || taskReferenceName === undefined) {
            throw new Error('Required parameter taskReferenceName was null or undefined when calling skipTaskFromWorkflow.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/api/workflow/${encodeURIComponent(String(workflowId))}/skiptask/${encodeURIComponent(String(taskReferenceName))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Start a new workflow. Returns the ID of the workflow instance that can be later used for tracking
     * 
     * @param body 
     * @param name 
     * @param version 
     * @param correlationId 
     * @param priority 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public startWorkflow(body: { [key: string]: any; }, name: string, version?: number, correlationId?: string, priority?: number, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public startWorkflow(body: { [key: string]: any; }, name: string, version?: number, correlationId?: string, priority?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public startWorkflow(body: { [key: string]: any; }, name: string, version?: number, correlationId?: string, priority?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public startWorkflow(body: { [key: string]: any; }, name: string, version?: number, correlationId?: string, priority?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling startWorkflow.');
        }

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling startWorkflow.');
        }




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (version !== undefined && version !== null) {
            queryParameters = queryParameters.set('version', <any>version);
        }
        if (correlationId !== undefined && correlationId !== null) {
            queryParameters = queryParameters.set('correlationId', <any>correlationId);
        }
        if (priority !== undefined && priority !== null) {
            queryParameters = queryParameters.set('priority', <any>priority);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<string>('post',`${this.basePath}/api/workflow/${encodeURIComponent(String(name))}`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Start a new workflow with StartWorkflowRequest, which allows task to be executed in a domain
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public startWorkflow1(body: StartWorkflowRequest, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public startWorkflow1(body: StartWorkflowRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public startWorkflow1(body: StartWorkflowRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public startWorkflow1(body: StartWorkflowRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling startWorkflow1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<string>('post',`${this.basePath}/api/workflow`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Terminate workflow execution
     * 
     * @param workflowId 
     * @param reason 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public terminate1(workflowId: string, reason?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public terminate1(workflowId: string, reason?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public terminate1(workflowId: string, reason?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public terminate1(workflowId: string, reason?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workflowId === null || workflowId === undefined) {
            throw new Error('Required parameter workflowId was null or undefined when calling terminate1.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (reason !== undefined && reason !== null) {
            queryParameters = queryParameters.set('reason', <any>reason);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/api/workflow/${encodeURIComponent(String(workflowId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
