/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StartWorkflow } from './startWorkflow';
import { TaskDetails } from './taskDetails';

export interface Action { 
    action?: Action.ActionEnum;
    startWorkflow?: StartWorkflow;
    completeTask?: TaskDetails;
    failTask?: TaskDetails;
    expandInlineJSON?: boolean;
}
export namespace Action {
    export type ActionEnum = 'start_workflow' | 'complete_task' | 'fail_task';
    export const ActionEnum = {
        StartWorkflow: 'start_workflow' as ActionEnum,
        CompleteTask: 'complete_task' as ActionEnum,
        FailTask: 'fail_task' as ActionEnum
    };
}