/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ByteString } from './byteString';
import { Descriptor } from './descriptor';
import { ParserAny } from './parserAny';
import { UnknownFieldSet } from './unknownFieldSet';


export interface Any {
    unknownFields?: UnknownFieldSet;
    initialized?: boolean;
    serializedSize?: number;
    parserForType?: ParserAny;
    defaultInstanceForType?: Any;
    typeUrl?: string;
    typeUrlBytes?: ByteString;
    value?: ByteString;
    allFields?: { [key: string]: any; };
    initializationErrorString?: string;
    descriptorForType?: Descriptor;
}
