/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EnumDescriptor } from './enumDescriptor';
import { FieldDescriptor } from './fieldDescriptor';
import { FileDescriptor } from './fileDescriptor';
import { MessageOptions } from './messageOptions';
import { OneofDescriptor } from './oneofDescriptor';


export interface Descriptor {
    index?: number;
    fullName?: string;
    file?: FileDescriptor;
    containingType?: Descriptor;
    nestedTypes?: Array<Descriptor>;
    enumTypes?: Array<EnumDescriptor>;
    fields?: Array<FieldDescriptor>;
    extensions?: Array<FieldDescriptor>;
    oneofs?: Array<OneofDescriptor>;
    options?: MessageOptions;
    extendable?: boolean;
    name?: string;
}
