/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ByteString } from './byteString';
import { Descriptor } from './descriptor';
import { DescriptorProtoOrBuilder } from './descriptorProtoOrBuilder';
import { EnumDescriptorProto } from './enumDescriptorProto';
import { EnumDescriptorProtoOrBuilder } from './enumDescriptorProtoOrBuilder';
import { ExtensionRange } from './extensionRange';
import { ExtensionRangeOrBuilder } from './extensionRangeOrBuilder';
import { FieldDescriptorProto } from './fieldDescriptorProto';
import { FieldDescriptorProtoOrBuilder } from './fieldDescriptorProtoOrBuilder';
import { MessageOptions } from './messageOptions';
import { MessageOptionsOrBuilder } from './messageOptionsOrBuilder';
import { OneofDescriptorProto } from './oneofDescriptorProto';
import { OneofDescriptorProtoOrBuilder } from './oneofDescriptorProtoOrBuilder';
import { ParserDescriptorProto } from './parserDescriptorProto';
import { ReservedRange } from './reservedRange';
import { ReservedRangeOrBuilder } from './reservedRangeOrBuilder';
import { UnknownFieldSet } from './unknownFieldSet';

export interface DescriptorProto { 
    unknownFields?: UnknownFieldSet;
    initialized?: boolean;
    options?: MessageOptions;
    fieldCount?: number;
    name?: string;
    nameBytes?: ByteString;
    serializedSize?: number;
    parserForType?: ParserDescriptorProto;
    defaultInstanceForType?: DescriptorProto;
    extensionRangeList?: Array<ExtensionRange>;
    reservedRangeList?: Array<ReservedRange>;
    reservedNameList?: Array<string>;
    nestedTypeCount?: number;
    enumTypeCount?: number;
    extensionCount?: number;
    oneofDeclCount?: number;
    fieldList?: Array<FieldDescriptorProto>;
    fieldOrBuilderList?: Array<FieldDescriptorProtoOrBuilder>;
    extensionList?: Array<FieldDescriptorProto>;
    extensionOrBuilderList?: Array<FieldDescriptorProtoOrBuilder>;
    nestedTypeList?: Array<DescriptorProto>;
    nestedTypeOrBuilderList?: Array<DescriptorProtoOrBuilder>;
    enumTypeList?: Array<EnumDescriptorProto>;
    enumTypeOrBuilderList?: Array<EnumDescriptorProtoOrBuilder>;
    extensionRangeOrBuilderList?: Array<ExtensionRangeOrBuilder>;
    extensionRangeCount?: number;
    oneofDeclList?: Array<OneofDescriptorProto>;
    oneofDeclOrBuilderList?: Array<OneofDescriptorProtoOrBuilder>;
    optionsOrBuilder?: MessageOptionsOrBuilder;
    reservedRangeOrBuilderList?: Array<ReservedRangeOrBuilder>;
    reservedRangeCount?: number;
    reservedNameCount?: number;
    initializationErrorString?: string;
    allFields?: { [key: string]: any; };
    descriptorForType?: Descriptor;
    memoizedSerializedSize?: number;
}