/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ByteString } from './byteString';
import { Descriptor } from './descriptor';
import { EnumOptions } from './enumOptions';
import { EnumOptionsOrBuilder } from './enumOptionsOrBuilder';
import { EnumReservedRange } from './enumReservedRange';
import { EnumReservedRangeOrBuilder } from './enumReservedRangeOrBuilder';
import { EnumValueDescriptorProto } from './enumValueDescriptorProto';
import { EnumValueDescriptorProtoOrBuilder } from './enumValueDescriptorProtoOrBuilder';
import { Message } from './message';
import { UnknownFieldSet } from './unknownFieldSet';

export interface EnumDescriptorProtoOrBuilder { 
    options?: EnumOptions;
    name?: string;
    nameBytes?: ByteString;
    reservedRangeList?: Array<EnumReservedRange>;
    reservedNameList?: Array<string>;
    optionsOrBuilder?: EnumOptionsOrBuilder;
    reservedRangeOrBuilderList?: Array<EnumReservedRangeOrBuilder>;
    reservedRangeCount?: number;
    reservedNameCount?: number;
    valueCount?: number;
    valueList?: Array<EnumValueDescriptorProto>;
    valueOrBuilderList?: Array<EnumValueDescriptorProtoOrBuilder>;
    initializationErrorString?: string;
    allFields?: { [key: string]: any; };
    descriptorForType?: Descriptor;
    unknownFields?: UnknownFieldSet;
    defaultInstanceForType?: Message;
    initialized?: boolean;
}