/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Descriptor } from './descriptor';
import { ParserEnumReservedRange } from './parserEnumReservedRange';
import { UnknownFieldSet } from './unknownFieldSet';

export interface EnumReservedRange { 
    unknownFields?: UnknownFieldSet;
    initialized?: boolean;
    start?: number;
    end?: number;
    serializedSize?: number;
    parserForType?: ParserEnumReservedRange;
    defaultInstanceForType?: EnumReservedRange;
    initializationErrorString?: string;
    allFields?: { [key: string]: any; };
    descriptorForType?: Descriptor;
    memoizedSerializedSize?: number;
}