/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Descriptor } from './descriptor';
import { EnumDescriptorProto } from './enumDescriptorProto';
import { EnumOptions } from './enumOptions';
import { EnumValueDescriptor } from './enumValueDescriptor';
import { FileDescriptor } from './fileDescriptor';

export interface EnumDescriptor { 
    index?: number;
    proto?: EnumDescriptorProto;
    fullName?: string;
    file?: FileDescriptor;
    containingType?: Descriptor;
    values?: Array<EnumValueDescriptor>;
    options?: EnumOptions;
    name?: string;
}