/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ByteString } from './byteString';
import { Descriptor } from './descriptor';
import { EnumValueOptions } from './enumValueOptions';
import { EnumValueOptionsOrBuilder } from './enumValueOptionsOrBuilder';
import { ParserEnumValueDescriptorProto } from './parserEnumValueDescriptorProto';
import { UnknownFieldSet } from './unknownFieldSet';

export interface EnumValueDescriptorProto { 
    unknownFields?: UnknownFieldSet;
    initialized?: boolean;
    options?: EnumValueOptions;
    number?: number;
    name?: string;
    nameBytes?: ByteString;
    serializedSize?: number;
    parserForType?: ParserEnumValueDescriptorProto;
    defaultInstanceForType?: EnumValueDescriptorProto;
    optionsOrBuilder?: EnumValueOptionsOrBuilder;
    initializationErrorString?: string;
    allFields?: { [key: string]: any; };
    descriptorForType?: Descriptor;
    memoizedSerializedSize?: number;
}