/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EnumDescriptor } from './enumDescriptor';
import { EnumValueOptions } from './enumValueOptions';
import { FileDescriptor } from './fileDescriptor';


export interface EnumValueDescriptor {
    index?: number;
    fullName?: string;
    file?: FileDescriptor;
    type?: EnumDescriptor;
    number?: number;
    options?: EnumValueOptions;
    name?: string;
}
