/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EnumDescriptor } from './enumDescriptor';
import { EnumValueDescriptorProto } from './enumValueDescriptorProto';
import { EnumValueOptions } from './enumValueOptions';
import { FileDescriptor } from './fileDescriptor';

export interface EnumValueDescriptor { 
    index?: number;
    proto?: EnumValueDescriptorProto;
    fullName?: string;
    file?: FileDescriptor;
    type?: EnumDescriptor;
    options?: EnumValueOptions;
    number?: number;
    name?: string;
}