/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ByteString } from './byteString';
import { Descriptor } from './descriptor';
import { FieldOptions } from './fieldOptions';
import { FieldOptionsOrBuilder } from './fieldOptionsOrBuilder';
import { ParserFieldDescriptorProto } from './parserFieldDescriptorProto';
import { UnknownFieldSet } from './unknownFieldSet';

export interface FieldDescriptorProto { 
    unknownFields?: UnknownFieldSet;
    initialized?: boolean;
    options?: FieldOptions;
    number?: number;
    label?: FieldDescriptorProto.LabelEnum;
    name?: string;
    typeName?: string;
    type?: FieldDescriptorProto.TypeEnum;
    defaultValue?: string;
    nameBytes?: ByteString;
    jsonName?: string;
    serializedSize?: number;
    parserForType?: ParserFieldDescriptorProto;
    defaultInstanceForType?: FieldDescriptorProto;
    proto3Optional?: boolean;
    oneofIndex?: number;
    extendee?: string;
    optionsOrBuilder?: FieldOptionsOrBuilder;
    typeNameBytes?: ByteString;
    extendeeBytes?: ByteString;
    defaultValueBytes?: ByteString;
    jsonNameBytes?: ByteString;
    initializationErrorString?: string;
    allFields?: { [key: string]: any; };
    descriptorForType?: Descriptor;
    memoizedSerializedSize?: number;
}
export namespace FieldDescriptorProto {
    export type LabelEnum = 'LABEL_OPTIONAL' | 'LABEL_REQUIRED' | 'LABEL_REPEATED';
    export const LabelEnum = {
        OPTIONAL: 'LABEL_OPTIONAL' as LabelEnum,
        REQUIRED: 'LABEL_REQUIRED' as LabelEnum,
        REPEATED: 'LABEL_REPEATED' as LabelEnum
    };
    export type TypeEnum = 'TYPE_DOUBLE' | 'TYPE_FLOAT' | 'TYPE_INT64' | 'TYPE_UINT64' | 'TYPE_INT32' | 'TYPE_FIXED64' | 'TYPE_FIXED32' | 'TYPE_BOOL' | 'TYPE_STRING' | 'TYPE_GROUP' | 'TYPE_MESSAGE' | 'TYPE_BYTES' | 'TYPE_UINT32' | 'TYPE_ENUM' | 'TYPE_SFIXED32' | 'TYPE_SFIXED64' | 'TYPE_SINT32' | 'TYPE_SINT64';
    export const TypeEnum = {
        DOUBLE: 'TYPE_DOUBLE' as TypeEnum,
        FLOAT: 'TYPE_FLOAT' as TypeEnum,
        INT64: 'TYPE_INT64' as TypeEnum,
        UINT64: 'TYPE_UINT64' as TypeEnum,
        INT32: 'TYPE_INT32' as TypeEnum,
        FIXED64: 'TYPE_FIXED64' as TypeEnum,
        FIXED32: 'TYPE_FIXED32' as TypeEnum,
        BOOL: 'TYPE_BOOL' as TypeEnum,
        STRING: 'TYPE_STRING' as TypeEnum,
        GROUP: 'TYPE_GROUP' as TypeEnum,
        MESSAGE: 'TYPE_MESSAGE' as TypeEnum,
        BYTES: 'TYPE_BYTES' as TypeEnum,
        UINT32: 'TYPE_UINT32' as TypeEnum,
        ENUM: 'TYPE_ENUM' as TypeEnum,
        SFIXED32: 'TYPE_SFIXED32' as TypeEnum,
        SFIXED64: 'TYPE_SFIXED64' as TypeEnum,
        SINT32: 'TYPE_SINT32' as TypeEnum,
        SINT64: 'TYPE_SINT64' as TypeEnum
    };
}