/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Descriptor } from './descriptor';
import { EnumDescriptor } from './enumDescriptor';
import { FieldDescriptor } from './fieldDescriptor';
import { FileDescriptorProto } from './fileDescriptorProto';
import { FileOptions } from './fileOptions';
import { ServiceDescriptor } from './serviceDescriptor';

export interface FileDescriptor { 
    proto?: FileDescriptorProto;
    messageTypes?: Array<Descriptor>;
    enumTypes?: Array<EnumDescriptor>;
    services?: Array<ServiceDescriptor>;
    extensions?: Array<FieldDescriptor>;
    dependencies?: Array<FileDescriptor>;
    publicDependencies?: Array<FileDescriptor>;
    options?: FileOptions;
    fullName?: string;
    name?: string;
    _package?: string;
    file?: FileDescriptor;
    syntax?: FileDescriptor.SyntaxEnum;
}
export namespace FileDescriptor {
    export type SyntaxEnum = 'UNKNOWN' | 'PROTO2' | 'PROTO3';
    export const SyntaxEnum = {
        UNKNOWN: 'UNKNOWN' as SyntaxEnum,
        PROTO2: 'PROTO2' as SyntaxEnum,
        PROTO3: 'PROTO3' as SyntaxEnum
    };
}