/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ByteString } from './byteString';
import { Descriptor } from './descriptor';
import { DescriptorProto } from './descriptorProto';
import { DescriptorProtoOrBuilder } from './descriptorProtoOrBuilder';
import { EnumDescriptorProto } from './enumDescriptorProto';
import { EnumDescriptorProtoOrBuilder } from './enumDescriptorProtoOrBuilder';
import { FieldDescriptorProto } from './fieldDescriptorProto';
import { FieldDescriptorProtoOrBuilder } from './fieldDescriptorProtoOrBuilder';
import { FileOptions } from './fileOptions';
import { FileOptionsOrBuilder } from './fileOptionsOrBuilder';
import { ParserFileDescriptorProto } from './parserFileDescriptorProto';
import { ServiceDescriptorProto } from './serviceDescriptorProto';
import { ServiceDescriptorProtoOrBuilder } from './serviceDescriptorProtoOrBuilder';
import { SourceCodeInfo } from './sourceCodeInfo';
import { SourceCodeInfoOrBuilder } from './sourceCodeInfoOrBuilder';
import { UnknownFieldSet } from './unknownFieldSet';

export interface FileDescriptorProto { 
    unknownFields?: UnknownFieldSet;
    initialized?: boolean;
    options?: FileOptions;
    name?: string;
    _package?: string;
    nameBytes?: ByteString;
    syntax?: string;
    serializedSize?: number;
    parserForType?: ParserFileDescriptorProto;
    defaultInstanceForType?: FileDescriptorProto;
    enumTypeCount?: number;
    extensionCount?: number;
    extensionList?: Array<FieldDescriptorProto>;
    extensionOrBuilderList?: Array<FieldDescriptorProtoOrBuilder>;
    enumTypeList?: Array<EnumDescriptorProto>;
    enumTypeOrBuilderList?: Array<EnumDescriptorProtoOrBuilder>;
    optionsOrBuilder?: FileOptionsOrBuilder;
    publicDependencyCount?: number;
    dependencyCount?: number;
    messageTypeCount?: number;
    serviceCount?: number;
    packageBytes?: ByteString;
    dependencyList?: Array<string>;
    publicDependencyList?: Array<number>;
    weakDependencyList?: Array<number>;
    weakDependencyCount?: number;
    messageTypeList?: Array<DescriptorProto>;
    messageTypeOrBuilderList?: Array<DescriptorProtoOrBuilder>;
    serviceList?: Array<ServiceDescriptorProto>;
    serviceOrBuilderList?: Array<ServiceDescriptorProtoOrBuilder>;
    sourceCodeInfo?: SourceCodeInfo;
    sourceCodeInfoOrBuilder?: SourceCodeInfoOrBuilder;
    syntaxBytes?: ByteString;
    initializationErrorString?: string;
    allFields?: { [key: string]: any; };
    descriptorForType?: Descriptor;
    memoizedSerializedSize?: number;
}