/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ByteString } from './byteString';
import { Descriptor } from './descriptor';
import { Message } from './message';
import { UnknownFieldSet } from './unknownFieldSet';

export interface LocationOrBuilder { 
    pathList?: Array<number>;
    pathCount?: number;
    spanList?: Array<number>;
    spanCount?: number;
    leadingComments?: string;
    leadingCommentsBytes?: ByteString;
    trailingComments?: string;
    trailingCommentsBytes?: ByteString;
    leadingDetachedCommentsList?: Array<string>;
    leadingDetachedCommentsCount?: number;
    initializationErrorString?: string;
    allFields?: { [key: string]: any; };
    descriptorForType?: Descriptor;
    unknownFields?: UnknownFieldSet;
    defaultInstanceForType?: Message;
    initialized?: boolean;
}