/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Descriptor } from './descriptor';
import { ParserMessageOptions } from './parserMessageOptions';
import { UninterpretedOption } from './uninterpretedOption';
import { UninterpretedOptionOrBuilder } from './uninterpretedOptionOrBuilder';
import { UnknownFieldSet } from './unknownFieldSet';

export interface MessageOptions { 
    unknownFields?: UnknownFieldSet;
    initialized?: boolean;
    messageSetWireFormat?: boolean;
    deprecated?: boolean;
    mapEntry?: boolean;
    serializedSize?: number;
    parserForType?: ParserMessageOptions;
    defaultInstanceForType?: MessageOptions;
    noStandardDescriptorAccessor?: boolean;
    uninterpretedOptionList?: Array<UninterpretedOption>;
    uninterpretedOptionOrBuilderList?: Array<UninterpretedOptionOrBuilder>;
    uninterpretedOptionCount?: number;
    allFields?: { [key: string]: any; };
    allFieldsRaw?: { [key: string]: any; };
    initializationErrorString?: string;
    descriptorForType?: Descriptor;
    memoizedSerializedSize?: number;
}