/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Descriptor } from './descriptor';
import { MessageLite } from './messageLite';
import { ParserMessage } from './parserMessage';
import { UnknownFieldSet } from './unknownFieldSet';


export interface Message {
    parserForType?: ParserMessage;
    serializedSize?: number;
    initialized?: boolean;
    defaultInstanceForType?: MessageLite;
    allFields?: { [key: string]: any; };
    initializationErrorString?: string;
    descriptorForType?: Descriptor;
    unknownFields?: UnknownFieldSet;
}
