/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Descriptor } from './descriptor';
import { MessageLite } from './messageLite';
import { ParserMessage } from './parserMessage';
import { UnknownFieldSet } from './unknownFieldSet';

export interface Message { 
    parserForType?: ParserMessage;
    serializedSize?: number;
    initialized?: boolean;
    defaultInstanceForType?: MessageLite;
    initializationErrorString?: string;
    allFields?: { [key: string]: any; };
    descriptorForType?: Descriptor;
    unknownFields?: UnknownFieldSet;
}