/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Descriptor } from './descriptor';
import { FileDescriptor } from './fileDescriptor';
import { MethodOptions } from './methodOptions';
import { ServiceDescriptor } from './serviceDescriptor';


export interface MethodDescriptor {
    index?: number;
    fullName?: string;
    file?: FileDescriptor;
    service?: ServiceDescriptor;
    inputType?: Descriptor;
    outputType?: Descriptor;
    options?: MethodOptions;
    name?: string;
}
