/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ByteString } from './byteString';
import { Descriptor } from './descriptor';
import { MethodOptions } from './methodOptions';
import { MethodOptionsOrBuilder } from './methodOptionsOrBuilder';
import { ParserMethodDescriptorProto } from './parserMethodDescriptorProto';
import { UnknownFieldSet } from './unknownFieldSet';

export interface MethodDescriptorProto { 
    unknownFields?: UnknownFieldSet;
    initialized?: boolean;
    options?: MethodOptions;
    inputType?: string;
    name?: string;
    outputType?: string;
    nameBytes?: ByteString;
    serializedSize?: number;
    parserForType?: ParserMethodDescriptorProto;
    defaultInstanceForType?: MethodDescriptorProto;
    optionsOrBuilder?: MethodOptionsOrBuilder;
    clientStreaming?: boolean;
    serverStreaming?: boolean;
    inputTypeBytes?: ByteString;
    outputTypeBytes?: ByteString;
    initializationErrorString?: string;
    allFields?: { [key: string]: any; };
    descriptorForType?: Descriptor;
    memoizedSerializedSize?: number;
}