/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Descriptor } from './descriptor';
import { ParserMethodOptions } from './parserMethodOptions';
import { UninterpretedOption } from './uninterpretedOption';
import { UninterpretedOptionOrBuilder } from './uninterpretedOptionOrBuilder';
import { UnknownFieldSet } from './unknownFieldSet';

export interface MethodOptions { 
    unknownFields?: UnknownFieldSet;
    initialized?: boolean;
    deprecated?: boolean;
    serializedSize?: number;
    parserForType?: ParserMethodOptions;
    defaultInstanceForType?: MethodOptions;
    uninterpretedOptionList?: Array<UninterpretedOption>;
    uninterpretedOptionOrBuilderList?: Array<UninterpretedOptionOrBuilder>;
    uninterpretedOptionCount?: number;
    idempotencyLevel?: MethodOptions.IdempotencyLevelEnum;
    initializationErrorString?: string;
    allFields?: { [key: string]: any; };
    descriptorForType?: Descriptor;
    allFieldsRaw?: { [key: string]: any; };
    memoizedSerializedSize?: number;
}
export namespace MethodOptions {
    export type IdempotencyLevelEnum = 'IDEMPOTENCY_UNKNOWN' | 'NO_SIDE_EFFECTS' | 'IDEMPOTENT';
    export const IdempotencyLevelEnum = {
        IDEMPOTENCYUNKNOWN: 'IDEMPOTENCY_UNKNOWN' as IdempotencyLevelEnum,
        NOSIDEEFFECTS: 'NO_SIDE_EFFECTS' as IdempotencyLevelEnum,
        IDEMPOTENT: 'IDEMPOTENT' as IdempotencyLevelEnum
    };
}