/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ByteString } from './byteString';
import { Descriptor } from './descriptor';
import { Message } from './message';
import { UnknownFieldSet } from './unknownFieldSet';


export interface NamePartOrBuilder {
    isExtension?: boolean;
    namePartBytes?: ByteString;
    namePart?: string;
    allFields?: { [key: string]: any; };
    initializationErrorString?: string;
    defaultInstanceForType?: Message;
    descriptorForType?: Descriptor;
    unknownFields?: UnknownFieldSet;
    initialized?: boolean;
}
