/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ByteString } from './byteString';
import { Descriptor } from './descriptor';
import { ParserNamePart } from './parserNamePart';
import { UnknownFieldSet } from './unknownFieldSet';


export interface NamePart {
    unknownFields?: UnknownFieldSet;
    isExtension?: boolean;
    namePartBytes?: ByteString;
    namePart?: string;
    initialized?: boolean;
    serializedSize?: number;
    parserForType?: ParserNamePart;
    defaultInstanceForType?: NamePart;
    allFields?: { [key: string]: any; };
    initializationErrorString?: string;
    descriptorForType?: Descriptor;
}
