/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ByteString } from './byteString';
import { Descriptor } from './descriptor';
import { OneofOptions } from './oneofOptions';
import { OneofOptionsOrBuilder } from './oneofOptionsOrBuilder';
import { ParserOneofDescriptorProto } from './parserOneofDescriptorProto';
import { UnknownFieldSet } from './unknownFieldSet';

export interface OneofDescriptorProto { 
    unknownFields?: UnknownFieldSet;
    initialized?: boolean;
    options?: OneofOptions;
    name?: string;
    nameBytes?: ByteString;
    serializedSize?: number;
    parserForType?: ParserOneofDescriptorProto;
    defaultInstanceForType?: OneofDescriptorProto;
    optionsOrBuilder?: OneofOptionsOrBuilder;
    initializationErrorString?: string;
    allFields?: { [key: string]: any; };
    descriptorForType?: Descriptor;
    memoizedSerializedSize?: number;
}