/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Descriptor } from './descriptor';
import { FieldDescriptor } from './fieldDescriptor';
import { FileDescriptor } from './fileDescriptor';
import { OneofDescriptorProto } from './oneofDescriptorProto';
import { OneofOptions } from './oneofOptions';

export interface OneofDescriptor { 
    index?: number;
    proto?: OneofDescriptorProto;
    fullName?: string;
    file?: FileDescriptor;
    containingType?: Descriptor;
    fieldCount?: number;
    fields?: Array<FieldDescriptor>;
    options?: OneofOptions;
    name?: string;
    synthetic?: boolean;
}