/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface RerunWorkflowRequest {
    reRunFromWorkflowId?: string;
    workflowInput?: { [key: string]: any; };
    reRunFromTaskId?: string;
    taskInput?: { [key: string]: any; };
    correlationId?: string;
}
