/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Descriptor } from './descriptor';
import { ParserReservedRange } from './parserReservedRange';
import { UnknownFieldSet } from './unknownFieldSet';

export interface ReservedRange { 
    unknownFields?: UnknownFieldSet;
    initialized?: boolean;
    start?: number;
    end?: number;
    serializedSize?: number;
    parserForType?: ParserReservedRange;
    defaultInstanceForType?: ReservedRange;
    initializationErrorString?: string;
    allFields?: { [key: string]: any; };
    descriptorForType?: Descriptor;
    memoizedSerializedSize?: number;
}