/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaskSummary } from './taskSummary';


export interface SearchResultTaskSummary {
    totalHits?: number;
    results?: Array<TaskSummary>;
}
