/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileDescriptor } from './fileDescriptor';
import { MethodDescriptor } from './methodDescriptor';
import { ServiceDescriptorProto } from './serviceDescriptorProto';
import { ServiceOptions } from './serviceOptions';

export interface ServiceDescriptor { 
    index?: number;
    proto?: ServiceDescriptorProto;
    fullName?: string;
    file?: FileDescriptor;
    methods?: Array<MethodDescriptor>;
    options?: ServiceOptions;
    name?: string;
}