/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileDescriptor } from './fileDescriptor';
import { MethodDescriptor } from './methodDescriptor';
import { ServiceOptions } from './serviceOptions';


export interface ServiceDescriptor {
    index?: number;
    fullName?: string;
    file?: FileDescriptor;
    methods?: Array<MethodDescriptor>;
    options?: ServiceOptions;
    name?: string;
}
