/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Any } from './any';


export interface SkipTaskRequest {
    taskInput?: { [key: string]: any; };
    taskOutput?: { [key: string]: any; };
    taskInputMessage?: Any;
    taskOutputMessage?: Any;
}
