/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WorkflowDef } from './workflowDef';


export interface StartWorkflowRequest {
    name: string;
    version?: number;
    correlationId?: string;
    input?: { [key: string]: any; };
    taskToDomain?: { [key: string]: string; };
    workflowDef?: WorkflowDef;
    externalInputPayloadStoragePath?: string;
    priority?: number;
}
