/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Any } from './any';


export interface TaskDetails {
    workflowId?: string;
    taskRefName?: string;
    output?: { [key: string]: any; };
    outputMessage?: Any;
    taskId?: string;
}
