/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Any } from './any';
import { TaskExecLog } from './taskExecLog';


export interface TaskResult {
    workflowInstanceId?: string;
    taskId?: string;
    reasonForIncompletion?: string;
    callbackAfterSeconds?: number;
    workerId?: string;
    status?: TaskResult.StatusEnum;
    outputData?: { [key: string]: any; };
    outputMessage?: Any;
    logs?: Array<TaskExecLog>;
    externalOutputPayloadStoragePath?: string;
    subWorkflowId?: string;
}
export namespace TaskResult {
    export type StatusEnum = 'IN_PROGRESS' | 'FAILED' | 'FAILED_WITH_TERMINAL_ERROR' | 'COMPLETED';
    export const StatusEnum = {
        INPROGRESS: 'IN_PROGRESS' as StatusEnum,
        FAILED: 'FAILED' as StatusEnum,
        FAILEDWITHTERMINALERROR: 'FAILED_WITH_TERMINAL_ERROR' as StatusEnum,
        COMPLETED: 'COMPLETED' as StatusEnum
    }
}
