/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ByteString } from './byteString';
import { Descriptor } from './descriptor';
import { NamePart } from './namePart';
import { NamePartOrBuilder } from './namePartOrBuilder';
import { ParserUninterpretedOption } from './parserUninterpretedOption';
import { UnknownFieldSet } from './unknownFieldSet';


export interface UninterpretedOption {
    unknownFields?: UnknownFieldSet;
    stringValue?: ByteString;
    nameList?: Array<NamePart>;
    identifierValue?: string;
    identifierValueBytes?: ByteString;
    positiveIntValue?: number;
    negativeIntValue?: number;
    aggregateValue?: string;
    aggregateValueBytes?: ByteString;
    nameOrBuilderList?: Array<NamePartOrBuilder>;
    initialized?: boolean;
    doubleValue?: number;
    serializedSize?: number;
    parserForType?: ParserUninterpretedOption;
    defaultInstanceForType?: UninterpretedOption;
    nameCount?: number;
    allFields?: { [key: string]: any; };
    initializationErrorString?: string;
    descriptorForType?: Descriptor;
}
