/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Parser } from './parser';


export interface UnknownFieldSet {
    initialized?: boolean;
    serializedSizeAsMessageSet?: number;
    serializedSize?: number;
    parserForType?: Parser;
    defaultInstanceForType?: UnknownFieldSet;
}
