/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface WorkflowSummary {
    workflowType?: string;
    version?: number;
    workflowId?: string;
    correlationId?: string;
    startTime?: string;
    updateTime?: string;
    endTime?: string;
    status?: WorkflowSummary.StatusEnum;
    input?: string;
    output?: string;
    reasonForIncompletion?: string;
    executionTime?: number;
    event?: string;
    failedReferenceTaskNames?: string;
    externalInputPayloadStoragePath?: string;
    externalOutputPayloadStoragePath?: string;
    priority?: number;
    outputSize?: number;
    inputSize?: number;
}
export namespace WorkflowSummary {
    export type StatusEnum = 'RUNNING' | 'COMPLETED' | 'FAILED' | 'TIMED_OUT' | 'TERMINATED' | 'PAUSED';
    export const StatusEnum = {
        RUNNING: 'RUNNING' as StatusEnum,
        COMPLETED: 'COMPLETED' as StatusEnum,
        FAILED: 'FAILED' as StatusEnum,
        TIMEDOUT: 'TIMED_OUT' as StatusEnum,
        TERMINATED: 'TERMINATED' as StatusEnum,
        PAUSED: 'PAUSED' as StatusEnum
    }
}
