/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SubWorkflowParams } from './subWorkflowParams';
import { Task } from './task';
import { TaskDef } from './taskDef';


export interface WorkflowTask {
    name?: string;
    taskReferenceName?: string;
    description?: string;
    inputParameters?: { [key: string]: any; };
    type?: string;
    dynamicTaskNameParam?: string;
    caseValueParam?: string;
    caseExpression?: string;
    scriptExpression?: string;
    decisionCases?: { [key: string]: Array<WorkflowTask>; };
    dynamicForkJoinTasksParam?: string;
    dynamicForkTasksParam?: string;
    dynamicForkTasksInputParamName?: string;
    defaultCase?: Array<WorkflowTask>;
    forkTasks?: Array<Array<WorkflowTask>>;
    startDelay?: number;
    subWorkflowParam?: SubWorkflowParams;
    joinOn?: Array<string>;
    sink?: string;
    optional?: boolean;
    taskDefinition?: TaskDef;
    rateLimited?: boolean;
    defaultExclusiveJoinTask?: Array<string>;
    asyncComplete?: boolean;
    loopCondition?: string;
    loopOver?: Array<WorkflowTask>;
    retryCount?: number;
    task?: Task
}
